=== JamshidSmailybazghaleh/SKOS/sdkc/schemas/knowledge-object.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",

  "title": "SDKC Knowledge Object",

  "description": "Standard Knowledge Object for Smaily Knowledge Development Core (SDKC).",

  "type": "object",

  "required": [

    "id",

    "type",

    "title",

    "version",

    "status",

    "metadata",

    "content"

  ],

  "properties": {

    "id": {

      "type": "string"

    },

    "type": {

      "type": "string"

    },

    "title": {

      "type": "string"

    },

    "description": {

      "type": "string"

    },

    "version": {

      "type": "string"

    },

    "status": {

      "type": "string"

    },

    "repository": {

      "type": "string"

    },

    "metadata": {

      "type": "object",

      "properties": {

        "author": {

          "type": "string"

        },

        "language": {

          "type": "string"

        },

        "category": {

          "type": "string"

        },

        "tags": {

          "type": "array",

          "items": {

            "type": "string"

          }

        },

        "created": {

          "type": "string"

        },

        "modified": {

          "type": "string"

        },

        "checksum": {

          "type": "string"

        }

      }

    },

    "content": {

      "type": "object"

    },

    "relations": {

      "type": "array",

      "items": {

        "type": "object",

        "properties": {

          "type": {

            "type": "string"

          },

          "target": {

            "type": "string"

          }

        }

      }

    }

  }

}

=== JamshidSmailybazghaleh/SKOS/sdkc/objects/books/BOOK-000001.json
{
  "id": "BOOK-000001",

  "type": "BOOK",

  "title": "Hekmat Noor",

  "description": "Knowledge Object",

  "version": "1.0",

  "status": "ACTIVE",

  "repository": "SDKC",

  "metadata": {

    "author": "Jamshid Smaily",

    "language": "Persian",

    "category": "Philosophy",

    "tags": [

      "Wisdom",

      "Knowledge",

      "SKOS"

    ],

    "created": "2026-07-28",

    "modified": "2026-07-28",

    "checksum": ""

  },

  "content": {

    "manifest": "manifest.json",

    "chapters": [

    ],

    "resources": [

    ]

  },

  "relations": [

    {

      "type": "PROJECT",

      "target": "PRJ-000001"

    }

  ]

}
